#Q1.What is the total revenue generated by the company?
#Business Problem: Measure overall business performance.

SELECT SUM(QUANTITYORDERED * PRICEEACH) AS Total_Revenue
FROM VEHICAL_SALES;

#Q2. Which countries generate the highest sales revenue?
#Business Problem: Identify top-performing markets.

SELECT COUNTRY,
       SUM(QUANTITYORDERED * PRICEEACH) AS Total_Sales
FROM VEHICAL_SALES
GROUP BY COUNTRY
ORDER BY Total_Sales DESC;

#Q3. Which customers contribute the most revenue?
#Business Problem: Identify high-value customers.

SELECT CUSTOMERNAME,
       SUM(QUANTITYORDERED * PRICEEACH) AS Total_Sales
FROM VEHICAL_SALES
GROUP BY CUSTOMERNAME
ORDER BY Total_Sales DESC
LIMIT 10;

#Q4. Which product lines generate the highest revenue?
#Business Problem: Determine the most profitable vehicle categories.

SELECT PRODUCTLINE,
       SUM(QUANTITYORDERED * PRICEEACH) AS Total_Sales
FROM VEHICAL_SALES
GROUP BY PRODUCTLINE
ORDER BY Total_Sales DESC;

#Q5. what are Best Product Line in Every Country?
#Business Problem: Understand regional preferences.

WITH country_product_sales AS (
    SELECT
        COUNTRY,
        PRODUCTLINE,
        SUM(QUANTITYORDERED * PRICEEACH) AS revenue,
        ROW_NUMBER() OVER(
            PARTITION BY COUNTRY
            ORDER BY SUM(QUANTITYORDERED * PRICEEACH) DESC
        ) rn
    FROM VEHICAL_SALES
    GROUP BY COUNTRY, PRODUCTLINE
)

SELECT
    COUNTRY,
    PRODUCTLINE,
    revenue
FROM country_product_sales
WHERE rn = 1
ORDER BY Revenue DESC;

#Q6. What are the monthly sales trends?
#Business Problem: Identify seasonality and demand fluctuations.

SELECT
    CAST(strftime('%Y', ORDERDATE) AS INTEGER) AS Year,
    CAST(strftime('%m', ORDERDATE) AS INTEGER) AS Month,
    SUM(QUANTITYORDERED * PRICEEACH) AS Revenue
FROM VEHICAL_SALES
GROUP BY Year, Month
ORDER BY Year, Month;

#Q7. Which states generate the most revenue?
#Business Problem: Identify high-performing regions.

SELECT STATE,
       SUM(QUANTITYORDERED * PRICEEACH) AS Revenue
FROM VEHICAL_SALES
GROUP BY STATE
ORDER BY Revenue DESC;

#Q8. What percentage of revenue comes from each product line?
#Business Problem: Understand revenue concentration.

SELECT PRODUCTLINE,
       ROUND(
       SUM(QUANTITYORDERED * PRICEEACH) * 100.0 /
       SUM(SUM(QUANTITYORDERED * PRICEEACH)) OVER (),2
       ) AS Revenue_Percentage
FROM VEHICAL_SALES
GROUP BY PRODUCTLINE
ORDER BY Revenue_Percentage DESC;

#Q9. Which customers purchase the greatest variety of products?
#Business Problem: Identify diversified customers.

SELECT CUSTOMERNAME,
       COUNT(DISTINCT PRODUCTCODE) AS Products_Purchased
FROM VEHICAL_SALES
GROUP BY CUSTOMERNAME
ORDER BY Products_Purchased DESC;

#Q10. Which product line performs best in each country?
#Business Problem: Understand regional product preferences.

SELECT COUNTRY,
       PRODUCTLINE,
       SUM(QUANTITYORDERED * PRICEEACH) AS Revenue
FROM VEHICAL_SALES
GROUP BY COUNTRY, PRODUCTLINE
ORDER BY COUNTRY, Revenue DESC;

#Q11. Rank product lines by total sales
SELECT PRODUCTLINE,
       SUM(QUANTITYORDERED * PRICEEACH) AS Revenue,
       RANK() OVER(
            ORDER BY SUM(QUANTITYORDERED * PRICEEACH) DESC
		 ) AS Sales_Rank
FROM VEHICAL_SALES
GROUP BY PRODUCTLINE;

#Q11. What is the revenue Lost Due to Cancelled / Non-Shipped Orders?
#Business Problem: Revenue leakage

WITH status_revenue AS (
    SELECT
        STATUS,
        SUM(QUANTITYORDERED * PRICEEACH) AS revenue
    FROM VEHICAL_SALES
    GROUP BY STATUS
)

SELECT *
FROM status_revenue
WHERE STATUS <> 'Shipped';


	
